# Generated by Django 4.2.21 on 2025-08-05 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('goal_description', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(choices=[('Health', 'Health'), ('Work', 'Work'), ('Personal', 'Personal'), ('Other', 'Other')], default='Health', max_length=50)),
                ('periodicity', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=20)),
                ('frequency', models.IntegerField(default=1)),
                ('specific_days', models.JSONField(default=list)),
                ('preferred_time', models.TimeField(blank=True, null=True)),
                ('icon', models.CharField(default='🌟', max_length=10)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('duration_weeks', models.IntegerField(default=4)),
            ],
            options={
                'verbose_name_plural': 'Habits',
            },
        ),
    ]
