# Generated by Django 4.2.21 on 2025-08-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is this habit currently being tracked?'),
        ),
        migrations.AddField(
            model_name='habit',
            name='is_template',
            field=models.BooleanField(default=False, help_text='Is this a suggested/template habit?'),
        ),
        migrations.AddField(
            model_name='habit',
            name='paused_date',
            field=models.DateTimeField(blank=True, help_text='When habit was paused/stopped', null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='started_date',
            field=models.DateTimeField(blank=True, help_text='When user started actively tracking', null=True),
        ),
    ]
