# Generated by Django 5.2.1 on 2025-09-03 18:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_habit_is_active_habit_is_template_habit_paused_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HabitCompletion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "completion_date",
                    models.DateField(default=django.utils.timezone.now),
                ),
                (
                    "completed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "habit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completions",
                        to="habits.habit",
                    ),
                ),
            ],
            options={
                "ordering": ["-completion_date", "-completed_at"],
                "unique_together": {("habit", "completion_date")},
            },
        ),
    ]
