# Generated by Django 5.2.1 on 2025-09-06 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0003_habitcompletion"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="habit",
            name="is_template",
        ),
    ]
