# Generated by Django 5.2.1 on 2025-09-06 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0004_remove_habit_is_template"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="is_active",
            field=models.BooleanField(
                default=False, help_text="Is this habit currently being tracked?"
            ),
        ),
    ]
