# Generated by Django 5.2.1 on 2025-09-27 10:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0005_alter_habit_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="habit",
            name="paused_date",
        ),
        migrations.AddField(
            model_name="habit",
            name="end_date",
            field=models.DateField(
                blank=True, help_text="Optional end date for habit tracking", null=True
            ),
        ),
        migrations.AddField(
            model_name="habit",
            name="week_starts_on",
            field=models.IntegerField(
                choices=[
                    (0, "Sunday"),
                    (1, "Monday"),
                    (2, "Tuesday"),
                    (3, "Wednesday"),
                    (4, "Thursday"),
                    (5, "Friday"),
                    (6, "Saturday"),
                ],
                default=1,
                help_text="Day of week for weekly period calculation",
            ),
        ),
        migrations.AddField(
            model_name="habitcompletion",
            name="was_on_target_day",
            field=models.BooleanField(
                default=True,
                help_text="Was this completion on a target day for weekly habits",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="duration_weeks",
            field=models.IntegerField(
                blank=True, help_text="Optional duration in weeks", null=True
            ),
        ),
        migrations.CreateModel(
            name="PeriodCompletion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "completed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("completion_count", models.PositiveIntegerField(default=0)),
                (
                    "habit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="period_completions",
                        to="habits.habit",
                    ),
                ),
            ],
            options={
                "ordering": ["-period_start"],
                "unique_together": {("habit", "period_start", "period_end")},
            },
        ),
    ]
