# Generated by Django 5.2.1 on 2025-10-05 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0006_remove_habit_paused_date_habit_end_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HabitTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("goal_description", models.CharField(blank=True, max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Health", "Health"),
                            ("Work", "Work"),
                            ("Personal", "Personal"),
                            ("Other", "Other"),
                        ],
                        default="Health",
                        max_length=50,
                    ),
                ),
                (
                    "periodicity",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        default="daily",
                        max_length=20,
                    ),
                ),
                ("frequency", models.IntegerField(default=1)),
                ("specific_days", models.JSONField(default=list)),
                ("preferred_time", models.TimeField(blank=True, null=True)),
                ("icon", models.CharField(default="🌟", max_length=50)),
                ("week_starts_on", models.IntegerField(default=1)),
                ("duration_weeks", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Habit Templates",
            },
        ),
    ]
