# Generated by Django 5.2.1 on 2025-10-05 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0007_habittemplate"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="template",
            field=models.ForeignKey(
                blank=True,
                help_text="The template this habit was created from",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="habits_created",
                to="habits.habittemplate",
            ),
        ),
    ]
