# Generated by Django 4.2.21 on 2025-10-12 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0008_habit_template'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habit',
            options={},
        ),
    ]
