# Generated by Django 5.2.4 on 2025-10-19 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0009_alter_habit_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='habitcompletion',
            unique_together=set(),
        ),
    ]
