# Generated by Django 5.2.4 on 2025-10-19 16:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0010_alter_habitcompletion_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habit',
            options={'verbose_name_plural': 'Habits'},
        ),
        migrations.AlterField(
            model_name='habitcompletion',
            name='completed_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='The exact timestamp the user marked it complete.'),
        ),
        migrations.AlterField(
            model_name='habitcompletion',
            name='completion_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='The date the habit was completed for.'),
        ),
        migrations.AlterField(
            model_name='periodcompletion',
            name='completion_count',
            field=models.PositiveIntegerField(default=0, help_text='How many completions were logged in this period.'),
        ),
        migrations.AlterUniqueTogether(
            name='habitcompletion',
            unique_together={('habit', 'completion_date')},
        ),
    ]
