# Generated by Django 5.2.4 on 2025-10-26 10:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0011_alter_habit_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="habit",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="habitcompletion",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="habitcompletion",
            name="completed_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="habitcompletion",
            name="completion_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="periodcompletion",
            name="completion_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
